### ISSUE TITLE
This repository will be archived in 2 weeks!

### ISSUE THREAD

**Issue by railsrumble-admin** [micrum/knight-move#24]
Hello fellow rumbler! In an effort to clean up our GitHub organization and centralize operations, we'll be archiving this repository on April 16th, 2016. Please be sure to [migrate it](https://help.github.com/articles/transferring-a-repository/) to your personal GitHub account before that happens, and let us know if this is problematic for any reason. We're happy to help.

Why are we doing this? Because we've got some exciting new things on the way. In case you haven't heard, the [Rails Rumble](http://railsrumble.com/) and [Node Knockout](http://nodeknockout.com/) teams recently joined up to bring you [RumbleX](http://rumblex.com/), a new hackathon thinktank that will be bringing you both events on a unified platform this year, along with more great contests, including the recently announced [Angular Attack](http://angularattack.com/) (May 14-15)!

Questions? We've got answers; email us any time at hello@rumblex.com

**Comment by micrum** [comment]
transfered
